# -*- coding: utf-8 -*-
"""one away string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_DoaB-epvdyZo7Cw5EYkN0A6AJsaYok
"""

def oneaway_string(string1,string2):
  '''
  check if two strings are one or second edit away from other
  '''
  if len(string1)==0 or len(string2)==0:
    return True
  count=0
  for i in range(0,len(string1)):
    if string1[i]!=string2[i]:
      count+=1
    if count>1:

      return False
  return True

oneaway_string("pale","kalw")
oneaway_string("pale","pales")
oneaway_string("pale","tale")
oneaway_string("pale","bake")

