# -*- coding: utf-8 -*-
"""string compression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXij5vi44jEs1jNi3Y-sTizDDBs93rU3
"""

def stringCompression(Targetstring):
  '''
  string compression
  ====> example
              aabcccccaaa
              the above string become
              a2b1c5a3
  '''
  if len(Targetstring)==0:
    return Targetstring
  count=1
  count_dic={}
  final_string=''
  for i in range(1,len(Targetstring)):
    if Targetstring[i]==Targetstring[i-1]:
      count+=1
      print(count,"adding the target value",Targetstring[i])
    else:
      count_dic[Targetstring[i-1]]=count
      final_string=final_string+str(Targetstring[i-1])+str(count)
      count=1
      print(count,Targetstring[i])
  return final_string

stringCompression('aabcccaa')

